import { defineField, defineType } from "sanity";

export const contactType = defineType({
  name: "contact",
  title: "Kontak dan Peta",
  type: "document",
  fields: [
    defineField({ name: "heading", title: "Judul Bagian Kontak", type: "string" }),
    defineField({ name: "description", title: "Teks Pendukung", type: "text", rows: 4 }),
    defineField({ name: "phone", title: "Nomor Telepon", type: "string" }),
    defineField({ name: "whatsappNumber", title: "Nomor WhatsApp", type: "string", description: "Gunakan nomor lokal, misalnya 081299375577." }),
    defineField({ name: "whatsappButtonLabel", title: "Label Tombol WhatsApp", type: "string" }),
    defineField({ name: "email", title: "Email", type: "string", validation: (rule) => rule.email() }),
    defineField({ name: "address", title: "Alamat Lengkap", type: "text", rows: 4 }),
    defineField({ name: "areaCoverage", title: "Area Layanan", type: "string" }),
    defineField({ name: "showInteractiveMap", title: "Tampilkan Peta Interaktif", type: "boolean", initialValue: true, description: "Matikan jika peta belum ingin ditampilkan di website." }),
    defineField({ name: "mapLatitude", title: "Latitude Peta", type: "number", description: "Koordinat latitude lokasi kantor. Contoh area Kelapa Gading: -6.1499." }),
    defineField({ name: "mapLongitude", title: "Longitude Peta", type: "number", description: "Koordinat longitude lokasi kantor. Contoh area Kelapa Gading: 106.8916." }),
    defineField({ name: "mapZoom", title: "Zoom Peta", type: "number", initialValue: 15, description: "Angka zoom peta. Rekomendasi 14–16." }),
    defineField({ name: "mapMarkerLabel", title: "Label Marker Peta", type: "string", description: "Teks yang muncul saat marker lokasi diklik." }),
    defineField({ name: "googleMapsUrl", title: "Tautan Google Maps", type: "url", description: "Dipakai untuk tombol Open in Google Maps. Peta interaktif di website tetap memakai OpenStreetMap, bukan Google Maps API." }),
    defineField({ name: "googleMapsEmbedUrl", title: "Tautan Embed Google Maps", type: "url", description: "Field lama opsional. Peta interaktif website memakai OpenStreetMap, jadi field ini boleh dikosongkan." }),
    defineField({ name: "latitude", title: "Latitude Lama", type: "number", description: "Field lama untuk kompatibilitas. Gunakan Latitude Peta untuk pengaturan baru." }),
    defineField({ name: "longitude", title: "Longitude Lama", type: "number", description: "Field lama untuk kompatibilitas. Gunakan Longitude Peta untuk pengaturan baru." }),
    defineField({ name: "instagramUrl", title: "Tautan Instagram", type: "url" }),
    defineField({ name: "facebookUrl", title: "Tautan Facebook", type: "url" }),
    defineField({ name: "twitterUrl", title: "Tautan Twitter/X", type: "url" }),
    defineField({ name: "linkedinUrl", title: "Tautan LinkedIn", type: "url" }),
  ],
  preview: { prepare: () => ({ title: "Kontak dan Peta", subtitle: "Telepon, WhatsApp, alamat, dan media sosial" }) },
});
