import { defineField, defineType } from "sanity";

export const contactType = defineType({
  name: "contact",
  title: "Kontak dan Peta",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "contact", title: "Contact" },
    { name: "map", title: "Map" },
    { name: "social", title: "Social" },
  ],
  fields: [
    defineField({ name: "heading", title: "Judul Bagian Kontak", type: "string", group: "content", validation: (rule) => rule.max(120) }),
    defineField({ name: "description", title: "Teks Pendukung", type: "text", group: "content", rows: 4, validation: (rule) => rule.max(320).warning("Jaga teks singkat dan operasional.") }),
    defineField({ name: "whatsappButtonLabel", title: "Label Tombol WhatsApp", type: "string", group: "content", validation: (rule) => rule.max(40) }),
    defineField({ name: "phone", title: "Nomor Telepon", type: "string", group: "contact" }),
    defineField({ name: "whatsappNumber", title: "Nomor WhatsApp", type: "string", group: "contact", description: "Gunakan nomor lokal, misalnya 081299375577." }),
    defineField({ name: "email", title: "Email", type: "string", group: "contact", validation: (rule) => rule.email() }),
    defineField({ name: "address", title: "Alamat Lengkap", type: "text", group: "contact", rows: 4 }),
    defineField({ name: "areaCoverage", title: "Area Layanan", type: "string", group: "contact" }),
    defineField({ name: "showInteractiveMap", title: "Tampilkan Peta Interaktif", type: "boolean", group: "map", initialValue: true, description: "Matikan jika peta belum ingin ditampilkan di website." }),
    defineField({ name: "mapLatitude", title: "Latitude Peta", type: "number", group: "map", description: "Koordinat latitude lokasi kantor. Contoh area Kelapa Gading: -6.1499." }),
    defineField({ name: "mapLongitude", title: "Longitude Peta", type: "number", group: "map", description: "Koordinat longitude lokasi kantor. Contoh area Kelapa Gading: 106.8916." }),
    defineField({ name: "mapZoom", title: "Zoom Peta", type: "number", group: "map", initialValue: 15, validation: (rule) => rule.min(12).max(18).warning("Gunakan angka 12 sampai 18."), description: "Angka zoom peta. Rekomendasi 14–16." }),
    defineField({ name: "mapMarkerLabel", title: "Label Marker Peta", type: "string", group: "map", description: "Teks yang muncul saat marker lokasi diklik." }),
    defineField({ name: "googleMapsUrl", title: "Tautan Google Maps", type: "url", group: "map", description: "Dipakai untuk tombol Open in Google Maps. Peta interaktif di website tetap memakai OpenStreetMap, bukan Google Maps API." }),
    defineField({ name: "googleMapsEmbedUrl", title: "Tautan Embed Google Maps (legacy)", type: "url", group: "map", description: "Field lama opsional. Peta interaktif website memakai OpenStreetMap, jadi field ini boleh dikosongkan." }),
    defineField({ name: "latitude", title: "Latitude Lama", type: "number", group: "map", description: "Field lama untuk kompatibilitas. Gunakan Latitude Peta untuk pengaturan baru." }),
    defineField({ name: "longitude", title: "Longitude Lama", type: "number", group: "map", description: "Field lama untuk kompatibilitas. Gunakan Longitude Peta untuk pengaturan baru." }),
    defineField({ name: "instagramUrl", title: "Tautan Instagram", type: "url", group: "social" }),
    defineField({ name: "facebookUrl", title: "Tautan Facebook", type: "url", group: "social" }),
    defineField({ name: "twitterUrl", title: "Tautan Twitter/X", type: "url", group: "social" }),
    defineField({ name: "linkedinUrl", title: "Tautan LinkedIn", type: "url", group: "social" }),
  ],
  preview: { prepare: () => ({ title: "Kontak dan Peta", subtitle: "Telepon, WhatsApp, alamat, dan media sosial" }) },
});
